In [12]:
from IPython.display import display, HTML

display(HTML("""
<style>
    /* 1. UMUMIY KONTEYNER VA SHRIFT */
    .rendered_html, .jp-RenderedHTMLCommon, .jp-RenderedMarkdown {
        font-family: "Times New Roman", Times, serif !important;
        color: black !important;
        font-feature-settings: "kern" 1, "liga" 1, "clig" 1, "dlig" 1 !important;
        -webkit-font-smoothing: antialiased !important;
    }

    /* 2. MATNLAR: 1.5 oraliq, abzats va ro‘yxatlar */
    .rendered_html p, .jp-RenderedHTMLCommon p {
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-align: justify !important;
        text-indent: 1.25cm !important; /* Faqat p uchun abzats */
        margin: 0 !important;
    }

    /* Ro‘yxatlar uchun maxsus (nuqtalarni qaytarish) */
    .rendered_html ul, .jp-RenderedHTMLCommon ul {
        list-style-type: disc !important;
        margin-left: 2.5cm !important; /* Nuqtalar ko‘rinishi uchun surish */
        padding: 0 !important;
        text-indent: 0 !important;
    }

    .rendered_html li, .jp-RenderedHTMLCommon li {
        display: list-item !important; /* Block-dan list-item-ga qaytarish */
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-indent: 0 !important;
        margin: 0 !important;
    }

    .rendered_html p, .jp-RenderedHTMLCommon p {
        text-indent: 1.25cm !important;
    }

    /* 3. SARLAVHALAR: Markazda */
    .rendered_html h1, .jp-RenderedHTMLCommon h1,
    .rendered_html h2, .jp-RenderedHTMLCommon h2,
    .rendered_html h3, .jp-RenderedHTMLCommon h3,
    .rendered_html h4, .jp-RenderedHTMLCommon h4 {
        font-family: "Times New Roman", Times, serif !important;
        text-align: center !important;
        text-indent: 0 !important;
        margin: 0.5em 0 !important;
        font-weight: bold !important;
    }
    
    /* 4. KOD BLOKLARI VA PROMPTLARNI (In/Out) YASHIRISH */
    :root {
        --jp-code-font-size: 12pt !important;
    }

    /* "In [ ]" va "Out [ ]" yozuvlarini butunlay yo‘qotish */
    .jp-InputPrompt, .jp-OutputPrompt, .prompt, .input_prompt, .output_prompt {
        display: none !important;
        width: 0 !important;
        visibility: hidden !important;
    }

    /* Kod bloklarini chap chekkaga taqash */
    .jp-CodeCell .jp-Cell-inputWrapper, .cell.code_cell .input {
        margin-left: 0 !important;
        padding-left: 0 !important;
    }

    /* Sliderni yo‘qotish va qatorni majburan sindirish */
    .jp-CodeMirror, .CodeMirror, .CodeMirror-scroll, .CodeMirror-sizer, .CodeMirror-lines,
    .jp-OutputArea-output pre, .output_area pre, 
    .CodeMirror-code, .CodeMirror-line,
    code, kbd, samp {
        font-family: "Consolas", monospace !important;
        font-size: 12pt !important;
        text-indent: 0 !important;
        line-height: 1.3 !important;
        white-space: pre-wrap !important;
        word-wrap: break-word !important;
        word-break: break-all !important;
        overflow-x: visible !important;
        height: auto !important;
    }

    /* 5. BIRINCHI KATAKCHANI YASHIRISH VA TANLANGANDA OCHISH */
    /* Odatiy holatda mutlaqo yashirin va umuman joy egallamaydi */
    .jp-Notebook .jp-Cell:first-child:not(.jp-mod-selected), 
    .container div.cell.code_cell:first-of-type:not(.selected) {
        position: absolute !important;
        height: 0 !important;
        min-height: 0 !important;
        width: 0 !important;
        margin: 0 !important;
        padding: 0 !important;
        border: none !important;
        overflow: hidden !important;
        opacity: 0 !important;
        pointer-events: none !important;
        visibility: hidden !important;
    }


    /* Katakcha tanlanganda (Ctrl+A bosilganda) to‘liq ochiladi */
    .jp-Notebook .jp-Cell:first-child.jp-mod-selected,
    .container div.cell.code_cell:first-of-type.selected {
        position: relative !important;
        height: auto !important;
        width: 100% !important;
        opacity: 1 !important;
        overflow: visible !important;
        pointer-events: auto !important;
        visibility: visible !important;
    }
    
    /* Jadvallar ichidagi matnlarni 14pt qilish */
    .rendered_html table, .jp-RenderedHTMLCommon table,
    .rendered_html td, .jp-RenderedHTMLCommon td,
    .rendered_html th, .jp-RenderedHTMLCommon th {
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        color: black !important;
    }
    code, kbd, samp {
        white-space: nowrap !important;
    }
</style>
"""))


## 1.10. NumPy va tasodifiy ma’lumotlar bilan ishlash (NumPy and Random Data)

NumPy tasodifiy ma’lumotlarni samarali yaratish uchun kuchli `numpy.random` modulini taqdim etadi. Bu modul foydalanuvchilarga turli xil taqsimotlar asosida tasodifiy sonlar, tanlanmalar va massivlar yaratish imkonini beradi.



Ushbu modul yordamida **tasodifiy butun sonlar**, 0 va 1 oralig‘idagi **tasodifiy o‘nlik (float) sonlar** hamda normal, tekis (uniform) va boshqa statistik taqsimotlardan tasodifiy tanlanmalar yaratish mumkin. 

NumPy-da `randint()` funksiyasi

`numpy.random.randint()` funksiyasi belgilangan oraliqda tasodifiy butun sonlarni yaratish uchun ishlatiladi. U sizga tasodifiy butun sonlar bilan to‘ldirilgan har qanday shakldagi massivlarni yaratish imkonini beradi, bu esa simulyatsiyalar, testlash va raqamli tajribalarda juda foydalidir.



**Misol:**
* **Kirish:** 0 va 5 oralig‘ida butun sonlar yaratish.
* **Chiqish:** `[3 1 4 0 2]`
* **Izoh:** Har bir qiymat $[0, 5)$ oraliqdagi tasodifiy butun sondir.

### **Sintaksis**
`numpy.random.randint(low, high=None, size=None, dtype=int)`

**Parametrlar:**
* `low:` Natijada paydo bo‘lishi mumkin bo‘lgan eng kichik butun son.
* `high` (Ixtiyoriy): Yuqori chegara (bu son kirmaydi). Agar tushirib qoldirilsa, oraliq $[0, low)$ bo‘lib qoladi.
* `size` (Ixtiyoriy): Chiqish massivining shakli (masalan, `5`, `(2,3)`, `(2,3,4)`).
* `dtype` (Ixtiyoriy): Qaytariladigan sonlarning ma’lumot turi. Standart qiymat — `int`.

### **Misollar**

**1-misol:** Ushbu misol 0 va 4 oralig‘ida beshta tasodifiy butun sonni hosil qiladi va ularni bir o‘lchamli massivda saqlaydi.


In [3]:
import numpy as np

# 0 dan 5 gacha (5 kirmaydi) bo‘lgan 5 ta tasodifiy son
arr = np.random.randint(0, 5, size=5)
print(arr)

[2 1 4 3 0]


**Izoh:** E’tibor bering, `high` parametri (bizning holatda 5) natijaga kirmaydi, ya’ni eng katta chiqishi mumkin bo‘lgan son 4 ga teng. Agar siz faqat bitta son (masalan, `np.random.randint(10)`) bersangiz, NumPy 0 dan 9 gacha bo‘lgan bitta tasodifiy sonni qaytaradi.

**2-misol:** Ushbu misol 0 dan 9 gacha bo‘lgan tasodifiy butun sonlardan iborat $2 \times 3$ o‘lchamli matrisa yaratadi.


In [4]:
# 0 dan 10 gacha (10 kirmaydi) bo‘lgan sonlardan 2x3 matrisa yaratish
arr = np.random.randint(0, 10, size=(2, 3))
print(arr)

[[2 1 1]
 [8 7 5]]


**Izoh:**
* **`size=(2, 3)`**: 2 ta qator va 3 ta ustunni yaratadi.
* **0 dan 10 gacha**: Yuqori chegara 10 natijaga kirmaydi.

**3-misol:** Ushbu misol 5 va 15 oralig‘idagi qiymatlarga ega bo‘lgan 3D massiv ($2 \times 2 \times 4$) hosil qiladi.


In [5]:
# 5 dan 15 gacha bo‘lgan sonlardan 2x2x4 o‘lchamli 3D massiv yaratish
arr = np.random.randint(5, 15, size=(2, 2, 4))
print(arr)

[[[ 6 13  6  8]
  [12  9 14 11]]

 [[ 5 12 12  5]
  [12  7  5 14]]]


**Izoh:**
3D massivni bir nechta qatlamli (blokli) jadvallar to‘plami deb tasavvur qilish mumkin. Bu yerda bizda har biri $2 \times 4$ o‘lchamli bo‘lgan 2 ta blok (qavat) mavjud. Bu kabi ko‘p o‘lchamli tasodifiy massivlar neyron tarmoqlarning kirish qatlamlarini yoki rangli tasvirlarni (RGB) modellashtirishda keng qo‘llaniladi.

### **Python-da `numpy.random.rand()`**

`numpy.random.rand()` funksiyasi 0 va 1 oralig‘ida tasodifiy sonlar hosil qilish va ularni belgilangan shakldagi massivda saqlash uchun ishlatiladi. Ushbu asosiy misol hech qanday argumentlarsiz bitta tasodifiy o‘nlik son qanday hosil qilinishini ko‘rsatadi.



In [6]:
x = np.random.rand()
print(x)

0.5089186775468159


**Izoh:** Hech qanday argument uzatilmaganda, `np.random.rand()` 0 va 1 oralig‘idagi bitta tasodifiy suzuvchi nuqtali (float) sonni qaytaradi.

### **Sintaksis**
`numpy.random.rand(d0, d1, ..., dn)`

**Parametrlar:**
* `d0, d1, ..., dn`: Chiqish massivining o‘lchamlarini belgilovchi butun sonlar. Agar argumentlar berilmasa, bitta float qiymat qaytariladi.

### **Misollar**

**1-misol:** Ushbu misol 0 va 1 oralig‘idagi 5 ta tasodifiy qiymatdan iborat bir o‘lchamli massivni hosil qiladi.


In [8]:
arr = np.random.rand(5)
print(arr)

[0.83732645 0.11776098 0.47467783 0.7170912  0.01285636]


**Izoh:** `np.random.rand(5)` uzunligi 5 ga teng bo‘lgan, 0 va 1 oralig‘idagi tasodifiy qiymatlar bilan to‘ldirilgan 1D massivni yaratadi.

**2-misol:** Ushbu misol tasodifiy qiymatlar bilan to‘ldirilgan 3 ta qator va 4 ta ustundan iborat 2D massivni yaratadi.



In [9]:
arr = np.random.rand(3, 4)
print(arr)

[[0.82295294 0.15609542 0.37348397 0.49801752]
 [0.52110912 0.19313417 0.58685687 0.67092494]
 [0.85723305 0.42080441 0.08741364 0.75393022]]


**Izoh:** `np.random.rand(3, 4)` har bir elementi 0 va 1 oralig‘idagi tasodifiy qiymat bo‘lgan $3 \times 4$ o‘lchamli matrisani hosil qiladi. Bu funksiya "uniform distribution" (tekis taqsimot) bo‘yicha ishlaydi, ya’ni berilgan oraliqdagi har bir sonning tanlanish ehtimoli bir xil.

**3-misol:** Ushbu misol tasodifiy qiymatlardan foydalangan holda (2, 2, 2) shaklidagi 3D massivni qanday hosil qilishni ko‘rsatadi.


In [10]:
# 2x2x2 o‘lchamli 3D massiv yaratish
arr = np.random.rand(2, 2, 2)
print(arr)

[[[0.67441808 0.58025199]
  [0.35689233 0.14899294]]

 [[0.98031582 0.22789834]
  [0.51969953 0.77196225]]]


**Izoh:**
`np.random.rand(2, 2, 2)` barcha qiymatlari 0 va 1 oralig‘ida tasodifiy ravishda hosil qilingan uch o‘lchamli massivni yaratadi. Buni har biri $2 \times 2$ o‘lchamli bo‘lgan ikkita matrisadan iborat blok deb tasavvur qilish mumkin. Bu kabi yuqori o‘lchamli massivlar chuqur o‘qitish (Deep Learning) modellarida og‘irlik koeffitsientlarini (weights) tasodifiy initsializatsiya qilishda juda muhim rol o‘ynaydi.

### 📝 Nazorat savollari

### 1-daraja: Asosiy tushunchalar

1. NumPy-da tasodifiy sonlar bilan ishlash uchun asosan qaysi moduldan foydalaniladi?
2. `np.random.rand()` funksiyasi qanday oraliqdagi sonlarni generatsiya qiladi?
3. `np.random.randn()` funksiyasi yaratgan sonlar qanday matematik taqsimotga (distribution) asoslanadi?
4. Tasodifiy butun sonlarni yaratishda `np.random.randint()` funksiyasining `low` va `high` parametrlari nima vazifani bajaradi?

### 2-daraja: Funksiyalarning ishlash mexanizmi

5. `np.random.rand()` funksiyasiga bir nechta argument (masalan, `2, 2, 2`) berilsa, natijaviy massiv shakli qanday bo‘ladi?
6. Standart normal taqsimotda o‘rtacha qiymat (`mean`) va standart og‘ish (`variance`) necha bo‘lishi kutiladi?
7. `np.random.randint()` funksiyasida `high` qiymati natijaviy massiv tarkibiga kiradimi?
8. Tasodifiy sonlar generatsiyasida har safar bir xil natija olish uchun qaysi funksiyadan foydalanish tavsiya etiladi?

### 3-daraja: Amaliy tahlil va simulyatsiya

9. 3D massivlar (masalan, `2x2x2`) yaratishda tasodifiy sonlar generatsiyasining ahamiyatini tushuntiring.
10. Nima uchun ilmiy tadqiqotlar va mashinali o‘rganish modellarini sinashda normal taqsimotdan (`randn`) foydalanish muhim?
11. Berilgan oraliqdagi (masalan, 1 dan 100 gacha) tasodifiy butun sonlar massivini yaratish jarayonini izohlang.
12. Tasodifiy ma’lumotlar yordamida sun’iy datasetlar yaratishning amaliy afzalliklari nimada?