In [16]:
from IPython.display import display, HTML

display(HTML("""
<style>
    /* 1. UMUMIY KONTEYNER VA SHRIFT */
    .rendered_html, .jp-RenderedHTMLCommon, .jp-RenderedMarkdown {
        font-family: "Times New Roman", Times, serif !important;
        color: black !important;
        font-feature-settings: "kern" 1, "liga" 1, "clig" 1, "dlig" 1 !important;
        -webkit-font-smoothing: antialiased !important;
    }

    /* 2. MATNLAR: 1.5 oraliq, abzats va ro‘yxatlar */
    .rendered_html p, .jp-RenderedHTMLCommon p {
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-align: justify !important;
        text-indent: 1.25cm !important; /* Faqat p uchun abzats */
        margin: 0 !important;
    }

    /* Ro‘yxatlar uchun maxsus (nuqtalarni qaytarish) */
    .rendered_html ul, .jp-RenderedHTMLCommon ul {
        list-style-type: disc !important;
        margin-left: 2.5cm !important; /* Nuqtalar ko‘rinishi uchun surish */
        padding: 0 !important;
        text-indent: 0 !important;
    }

    .rendered_html li, .jp-RenderedHTMLCommon li {
        display: list-item !important; /* Block-dan list-item-ga qaytarish */
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-indent: 0 !important;
        margin: 0 !important;
    }

    .rendered_html p, .jp-RenderedHTMLCommon p {
        text-indent: 1.25cm !important;
    }

    /* 3. SARLAVHALAR: Markazda */
    .rendered_html h1, .jp-RenderedHTMLCommon h1,
    .rendered_html h2, .jp-RenderedHTMLCommon h2,
    .rendered_html h3, .jp-RenderedHTMLCommon h3,
    .rendered_html h4, .jp-RenderedHTMLCommon h4 {
        font-family: "Times New Roman", Times, serif !important;
        text-align: center !important;
        text-indent: 0 !important;
        margin: 0.5em 0 !important;
        font-weight: bold !important;
    }
    
    /* 4. KOD BLOKLARI VA PROMPTLARNI (In/Out) YASHIRISH */
    :root {
        --jp-code-font-size: 12pt !important;
    }

    /* "In [ ]" va "Out [ ]" yozuvlarini butunlay yo‘qotish */
    .jp-InputPrompt, .jp-OutputPrompt, .prompt, .input_prompt, .output_prompt {
        display: none !important;
        width: 0 !important;
        visibility: hidden !important;
    }

    /* Kod bloklarini chap chekkaga taqash */
    .jp-CodeCell .jp-Cell-inputWrapper, .cell.code_cell .input {
        margin-left: 0 !important;
        padding-left: 0 !important;
    }

    /* Sliderni yo‘qotish va qatorni majburan sindirish */
    .jp-CodeMirror, .CodeMirror, .CodeMirror-scroll, .CodeMirror-sizer, .CodeMirror-lines,
    .jp-OutputArea-output pre, .output_area pre, 
    .CodeMirror-code, .CodeMirror-line,
    code, kbd, samp {
        font-family: "Consolas", monospace !important;
        font-size: 12pt !important;
        text-indent: 0 !important;
        line-height: 1.3 !important;
        white-space: pre-wrap !important;
        word-wrap: break-word !important;
        word-break: break-all !important;
        overflow-x: visible !important;
        height: auto !important;
    }

    /* 5. BIRINCHI KATAKCHANI YASHIRISH VA TANLANGANDA OCHISH */
    /* Odatiy holatda mutlaqo yashirin va umuman joy egallamaydi */
    .jp-Notebook .jp-Cell:first-child:not(.jp-mod-selected), 
    .container div.cell.code_cell:first-of-type:not(.selected) {
        position: absolute !important;
        height: 0 !important;
        min-height: 0 !important;
        width: 0 !important;
        margin: 0 !important;
        padding: 0 !important;
        border: none !important;
        overflow: hidden !important;
        opacity: 0 !important;
        pointer-events: none !important;
        visibility: hidden !important;
    }


    /* Katakcha tanlanganda (Ctrl+A bosilganda) to‘liq ochiladi */
    .jp-Notebook .jp-Cell:first-child.jp-mod-selected,
    .container div.cell.code_cell:first-of-type.selected {
        position: relative !important;
        height: auto !important;
        width: 100% !important;
        opacity: 1 !important;
        overflow: visible !important;
        pointer-events: auto !important;
        visibility: visible !important;
    }
    
    /* Jadvallar ichidagi matnlarni 14pt qilish */
    .rendered_html table, .jp-RenderedHTMLCommon table,
    .rendered_html td, .jp-RenderedHTMLCommon td,
    .rendered_html th, .jp-RenderedHTMLCommon th {
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        color: black !important;
    }
</style>
"""))


## 1.5. Massiv shakli va uning o‘lchamlarini o‘zgartirish (Shaping & Reshaping in Array)

Massivning **shakli (shape)** har bir o‘lchamdagi elementlar soni sifatida ta’riflanadi. Unga massiv o‘lchamlarini ifodalovchi kortejni (tuple) qaytaruvchi `shape` atributi orqali kirish mumkin. Ushbu paragrafda NumPy massivining shaklini qanday o‘zgartirishni o‘rganamiz. Bu jarayon massiv shaklini qayta qurish (**reshaping**), yassilash (**flattening**) va muayyan vazifalarga moslashtirish uchun massiv tuzilmasini modifikatsiya qilishni o‘z ichiga oladi.

### 1.5.1. Massiv shaklini boshqarish (Shape Manipulation in NumPy)

Massivning **shakli (shape)** har bir o‘lchamdagi elementlar soni sifatida ta’riflanishi mumkin. **O‘lcham (dimension)** — bu massivning alohida elementini ko‘rsatish (aniqlash) uchun talab qilinadigan indekslar yoki pastki belgilar sonidir.

### **Massiv shaklini qanday olish mumkin?**

NumPy-da biz **`shape`** deb nomlangan atributdan foydalanamiz, u **kortej (tuple)** qaytaradi; kortej elementlari massivning mos keladigan o‘lchamlari uzunligini bildiradi.

* **Sintaksis:** `numpy.shape(massiv_nomi)`
* **Parametrlar:** Massiv parametr sifatida uzatiladi.
* **Qaytariladigan qiymat:** Elementlari massiv o‘lchamlarining uzunligini ko‘rsatuvchi kortej.

### **NumPy-da shakl manipulyatsiyasi (Shape Manipulation)**

Quyida Python-dagi NumPy kutubxonasida shakllar bilan ishlashni tushunish uchun misollar keltirilgan:

**1-misol: Massivlar shakli**
Ko'p o'lchamli massivning shaklini chop etish. Ushbu misolda mos ravishda 2D va 3D massivlarni ifodalovchi `arr1` va `arr2` nomli ikkita NumPy massivi yaratilgan. Har bir massivning shakli (shape) chop etilib, ularning o'lchamlari va har bir o'lcham bo'yicha hajmi ko'rsatilgan.


In [5]:
import numpy as np

# 2 o'lchamli (2-D) massiv yaratish
arr1 = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])

# 3 o'lchamli (3-D) massiv yaratish
arr2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr1.shape)
print(arr2.shape)

(2, 4)
(2, 2, 2)


**2-misol: `ndmin` yordamida massiv shaklini belgilash**

Ushbu misolda biz 2, 4, 6, 8, 10 qiymatlariga ega vektordan foydalangan holda `ndmin` parametri orqali massiv yaratamiz va oxirgi o‘lcham qiymatini tekshiramiz.


In [6]:
# 6 o'lchamli massiv yaratish
# ndmin parametridan foydalangan holda
arr = np.array([2, 4, 6, 8, 10], ndmin=6)

# Massivni chop etish
print(arr)

# Oxirgi o'lcham qiymati 5 ekanligini 
# va jami 6 ta o'lchamni tekshirish
print('massiv shakli :', arr.shape)

[[[[[[ 2  4  6  8 10]]]]]]
massiv shakli : (1, 1, 1, 1, 1, 5)


**Izoh:**
`ndmin=6` parametri NumPy-ga massiv kamida 6 o'lchamli bo'lishi kerakligini aytadi. Dastlabki 5 ta o'lcham "to'ldiruvchi" (har birida 1 tadan element) bo'lib xizmat qiladi, oxirgi (oltinchi) o'lcham esa biz kiritgan 5 ta elementni o'z ichiga oladi. Shuning uchun natija `(1, 1, 1, 1, 1, 5)` ko'rinishida chiqadi.

**3-misol: Kortejlar (tuples) massivining shakli**

Ushbu misolda biz har bir elementi kortejdan iborat bo‘lgan NumPy massivini yaratamiz va bunday massivning shakli (shape) qanday aniqlanishini ko‘rsatib beramiz.

In [7]:
# Kortejlar ro'yxatidan massiv yaratish
array_of_tuples = np.array([(1, 2), (3, 4), (5, 6), (7, 8)])

# Massivni ko'rsatish
print("Kortejlar massivi:")
print(array_of_tuples)

# Shaklni aniqlash va ko'rsatish
shape = array_of_tuples.shape
print("\nMassiv shakli:", shape)

Kortejlar massivi:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Massiv shakli: (4, 2)


**Izoh:**
NumPy kortejlar ro‘yxatini qabul qilganda, ularni avtomatik ravishda 2 o‘lchamli massivga (matritsaga) aylantiradi. Har bir kortej massivning bitta qatori deb hisoblanadi. Bu yerda 4 ta kortej bor va har birida 2 tadan element mavjud, shuning uchun massiv shakli **(4, 2)** bo‘ladi.

### 1.5.2. Massiv shaklini o'zgartirish (Array Reshaping)

NumPy-da shaklni o'zgartirish (**Reshaping**) — bu mavjud massivning ma'lumotlarini o'zgartirmasdan, uning o'lchamlarini modifikatsiya qilishdir. Buning uchun `reshape()` funksiyasidan foydalaniladi. U elementlarni yangi shaklga qayta tartiblaydi, bu esa mashinali o'rganish, matritsa amallari va ma'lumotlarni tayyorlashda juda foydalidir.



**1-misol:** Ushbu misol jami elementlar soniga mos keladigan qator va ustunlarni ko'rsatish orqali 1-D massivni 2-D massivga aylantiradi.

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
r = a.reshape(2, 3)
print(r)

[[1 2 3]
 [4 5 6]]



**Izoh:** `a.reshape(2, 3)` 6 ta elementni 2 ta qator va 3 ta ustunga joylashtirib, 2-D matritsani hosil qiladi.

**Sintaksis**
`array.reshape(shape)`

* **Parametr:** `shape` - Yangi o'lchamlarni belgilaydigan kortej (tuple). Bir o'lcham **-1** bo'lishi mumkin, bunda NumPy jami elementlar sonidan kelib chiqib, ushbu o'lchamni avtomatik hisoblab oladi.
* **Qaytaradi:** Yangi shaklga ega bo'lgan `ndarray`.

**2-misol:** Ushbu misol asl elementlarni har biri teng o‘lchamdagi 2-D qismlardan iborat bloklarga guruhlash orqali 3-D massiv yaratadi.

In [9]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
r = a.reshape(2, 2, 2)
print(r)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**Izoh:** `a.reshape(2, 2, 2)` massivni har biri 2x2 o‘lchamli matritsadan iborat bo‘lgan 2 ta blokka o‘zgartiradi va 3-D tuzilmani hosil qiladi.

**3-misol:** Ushbu misol bitta o‘lcham noma’lum bo‘lganda **-1** dan foydalanishni ko‘rsatadi. NumPy yetishmayotgan o‘lchamni avtomatik ravishda hisoblab chiqadi.


In [10]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
r = a.reshape(3, -1)
print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Izoh:** `a.reshape(3, -1)` NumPy-ga 3 ta qator yaratishni buyuradi va u qolgan o‘lchamni 4 ta ustun deb hisoblaydi, chunki $12 \div 3 = 4$.

### 1.5.3. NumPy massivlarini tekislash va tartibni o‘zgartirish (Flattening and Changing Order)

`flatten()` funksiyasi ko‘p o‘lchamli **NumPy massivini** bir o‘lchamli massivga o‘tkazish uchun ishlatiladi. U ma’lumotlarning yangi nusxasini yaratadi, shuning uchun asl massiv o‘zgarishsiz qoladi. Agar massivingizda qatorlar va ustunlar yoki undan ham ko‘proq o‘lchamlar bo‘lsa, `flatten()` barcha qiymatlarni birin-ketin to‘g‘ri chiziqli ro‘yxatga joylashtiradi.



**Misol:**

In [11]:
a = np.array([[5, 6], [7, 8]])
res = a.flatten()
print(res)

[5 6 7 8]


**Izoh:** Ushbu kod 2D NumPy massivini yaratadi va `flatten()` yordamida uni qatorlar tartibida (row-major order) 1D massivga aylantiradi. U asl massivni o‘zgartirmasdan, yangi `[5, 6, 7, 8]` massivini qaytaradi.

### **`ndarray.flatten()` sintaksisi**

`array.flatten(order='C')`

**Parametrlar:** `order` ({‘C’, ‘F’, ‘A’, ‘K’}) - ixtiyoriy
* **'C'**: Qatorlar bo‘yicha (C-uslubi) tartiblash.
* **'F'**: Ustunlar bo‘yicha (Fortran-uslubi) tartiblash.
* **'A'**: Agar massiv xotirada Fortran tartibida bo‘lsa ustunlar bo‘yicha, aks holda qatorlar bo‘yicha.
* **'K'**: Elementlar xotirada qanday ketma-ketlikda joylashgan bo‘lsa, shu tartibda yassilash.

**Qaytaradi:** Ko‘rsatilgan tartib bo‘yicha yassilangan kiruvchi massivning 1D nusxasini.

### **`ndarray.flatten()` uchun misollar**

**1-misol:** Ushbu misolda biz 2D NumPy massivini ustunlar bo‘yicha (column-major order, shuningdek, Fortran-uslubidagi tartib deb ham ataladi) yassilash uchun `flatten()` funksiyasini `'F'` parametri bilan ishlatamiz. Bu funksiya elementlarni qatorlar bo‘yicha emas, balki ustunma-ustun o‘qiydi deganidir.


In [12]:
a = np.array([[5, 6], [7, 8]])
res = a.flatten('F')
print(res)

[5 7 6 8]


**Izoh:** `flatten('F')` massivni ustunlar bo‘yicha (Fortran-uslubida) 1D massivga aylantiradi. Natija `[5, 7, 6, 8]` bo‘lib, elementlar ustunma-ustun tartibda joylashgan.

**2-misol:** Ushbu misolda biz ikkita 2D NumPy massivini yassilashni va so‘ngra ularni NumPy-ning `concatenate()` funksiyasi yordamida bitta 1D massivga birlashtirishni ko‘rib chiqamiz.


In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

res = np.concatenate((a.flatten(), b.flatten()))
print(res)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


**Izoh:** Ushbu kod `a` va `b` nomli ikkita 2D NumPy massivini 1D massivga yassilaydi va so‘ngra ularni birlashtiradi. Natijada har ikkala massivning yassilangan elementlarini o‘z ichiga olgan yagona 1D massiv hosil bo‘ladi.

**3-misol:** Ushbu misolda biz 2D NumPy massivini yassilashni va so‘ngra uning shakliga mos keladigan, nollar bilan to‘ldirilgan yangi 1D massivni yaratishni ko‘rib chiqamiz.


In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
res = np.zeros_like(a.flatten())
print(res)

[0 0 0 0 0 0]


**Izoh:** Ushbu kod `np.zeros_like()` funksiyasidan foydalanib, bir xil shakldagi, nollar bilan to‘ldirilgan yangi massiv yaratadi. Natija `a` massivining yassilangan shakliga mos keladigan nollardan iborat 1D massivdir.

**4-misol:** Ushbu misolda biz 2D NumPy massivini yaratamiz. So‘ngra yassilangan massivdagi barcha elementlar orasidan eng katta qiymatni topish uchun `max()` metodini qo‘llaymiz.


In [15]:
a = np.array([[4, 12, 8], [5, 9, 10], [7, 6, 11]])
res = a.flatten().max()
print(res)

12


**Izoh:** Ushbu kod `a` 2D NumPy massivini 1D massivga yassilaydi va keyin `.max()` yordamida eng katta qiymatni topadi. Natija **12** bo‘lib, u yassilangan massivdagi eng katta qiymatdir.