In [1]:
from IPython.display import display, HTML

display(HTML("""
<style>
    /* 1. UMUMIY KONTEYNER VA SHRIFT */
    .rendered_html, .jp-RenderedHTMLCommon, .jp-RenderedMarkdown {
        font-family: "Times New Roman", Times, serif !important;
        color: black !important;
        font-feature-settings: "kern" 1, "liga" 1, "clig" 1, "dlig" 1 !important;
        -webkit-font-smoothing: antialiased !important;
    }

    /* 2. MATNLAR: 1.5 oraliq, abzats va ro‘yxatlar */
    .rendered_html p, .jp-RenderedHTMLCommon p {
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-align: justify !important;
        text-indent: 1.25cm !important; /* Faqat p uchun abzats */
        margin: 0 !important;
    }

    /* Ro‘yxatlar uchun maxsus (nuqtalarni qaytarish) */
    .rendered_html ul, .jp-RenderedHTMLCommon ul {
        list-style-type: disc !important;
        margin-left: 2.5cm !important; /* Nuqtalar ko‘rinishi uchun surish */
        padding: 0 !important;
        text-indent: 0 !important;
    }

    .rendered_html li, .jp-RenderedHTMLCommon li {
        display: list-item !important; /* Block-dan list-item-ga qaytarish */
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-indent: 0 !important;
        margin: 0 !important;
    }

    .rendered_html p, .jp-RenderedHTMLCommon p {
        text-indent: 1.25cm !important;
    }

    /* 3. SARLAVHALAR: Markazda */
    .rendered_html h1, .jp-RenderedHTMLCommon h1,
    .rendered_html h2, .jp-RenderedHTMLCommon h2,
    .rendered_html h3, .jp-RenderedHTMLCommon h3,
    .rendered_html h4, .jp-RenderedHTMLCommon h4 {
        font-family: "Times New Roman", Times, serif !important;
        text-align: center !important;
        text-indent: 0 !important;
        margin: 0.5em 0 !important;
        font-weight: bold !important;
    }
    
    /* 4. KOD BLOKLARI VA PROMPTLARNI (In/Out) YASHIRISH */
    :root {
        --jp-code-font-size: 12pt !important;
    }

    /* "In [ ]" va "Out [ ]" yozuvlarini butunlay yo‘qotish */
    .jp-InputPrompt, .jp-OutputPrompt, .prompt, .input_prompt, .output_prompt {
        display: none !important;
        width: 0 !important;
        visibility: hidden !important;
    }

    /* Kod bloklarini chap chekkaga taqash */
    .jp-CodeCell .jp-Cell-inputWrapper, .cell.code_cell .input {
        margin-left: 0 !important;
        padding-left: 0 !important;
    }

    /* Sliderni yo‘qotish va qatorni majburan sindirish */
    .jp-CodeMirror, .CodeMirror, .CodeMirror-scroll, .CodeMirror-sizer, .CodeMirror-lines,
    .jp-OutputArea-output pre, .output_area pre, 
    .CodeMirror-code, .CodeMirror-line,
    code, kbd, samp {
        font-family: "Consolas", monospace !important;
        font-size: 12pt !important;
        text-indent: 0 !important;
        line-height: 1.3 !important;
        white-space: pre-wrap !important;
        word-wrap: break-word !important;
        word-break: break-all !important;
        overflow-x: visible !important;
        height: auto !important;
    }

    /* 5. BIRINCHI KATAKCHANI YASHIRISH VA TANLANGANDA OCHISH */
    /* Odatiy holatda mutlaqo yashirin va umuman joy egallamaydi */
    .jp-Notebook .jp-Cell:first-child:not(.jp-mod-selected), 
    .container div.cell.code_cell:first-of-type:not(.selected) {
        position: absolute !important;
        height: 0 !important;
        min-height: 0 !important;
        width: 0 !important;
        margin: 0 !important;
        padding: 0 !important;
        border: none !important;
        overflow: hidden !important;
        opacity: 0 !important;
        pointer-events: none !important;
        visibility: hidden !important;
    }


    /* Katakcha tanlanganda (Ctrl+A bosilganda) to‘liq ochiladi */
    .jp-Notebook .jp-Cell:first-child.jp-mod-selected,
    .container div.cell.code_cell:first-of-type.selected {
        position: relative !important;
        height: auto !important;
        width: 100% !important;
        opacity: 1 !important;
        overflow: visible !important;
        pointer-events: auto !important;
        visibility: visible !important;
    }
    
    /* Jadvallar ichidagi matnlarni 14pt qilish */
    .rendered_html table, .jp-RenderedHTMLCommon table,
    .rendered_html td, .jp-RenderedHTMLCommon td,
    .rendered_html th, .jp-RenderedHTMLCommon th {
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        color: black !important;
    }
</style>
"""))


## 1.7. Massivlarni birlashtirish, bo‘lish va agregatsiyalash (Combining, Splitting and Aggregating Arrays)

Massivlarni birlashtirish kichik massivlarni bitta yirik massivga jamlashni anglatadi. Massivlarni vertikal, gorizontal yoki istalgan maxsus o‘q bo‘ylab birlashtirish mumkin. Bu jarayon konkatenatsiya (ulash) va steklash (gorizontal, vertikal taxlash) kabi usullarni o‘z ichiga oladi.

### 1.7.1. NumPy massivlarini birlashtirish (Joining NumPy Arrays)

NumPy massivlarini birlashtirish bir nechta massivni bitta yirik massivga jamlashni anglatadi. Masalan, [1, 2] va [3, 4] massivlarini birlashtirish natijasida [1, 2, 3, 4] massivi hosil bo‘ladi. Keling, NumPy yordamida massivlarni birlashtirishning eng keng tarqalgan usullarini ko‘rib chiqamiz.

### **1. `numpy.concatenate()` funksiyasidan foydalanish**

`numpy.concatenate()` funksiyasi ikki yoki undan ortiq massivni yangi o‘lcham qo‘shmasdan, mavjud o‘q bo‘ylab birlashtiradi. Bu usul massivlarni oddiygina ulab qo‘yish uchun juda tez va samarali hisoblanadi.



**Misol**

In [3]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

# Massivlarni birlashtirish
res = np.concatenate((a, b))

print(res)

[1 2 3 4]


Ushbu kod NumPy-ning `concatenate` funksiyasidan foydalanib, massivlarni uchma-uch birlashtiradi va bitta uzun [1, 2, 3, 4] ro‘yxatiga aylantiradi.

**Eslatma:** Standart holatda (agar o‘q ko‘rsatilmasa) `concatenate` birinchi o‘q (`axis=0`) bo‘ylab ishlaydi. 1-D massivlar uchun bu ularni shunchaki yonma-yon ulab qo‘yishni anglatadi.

### **2. `numpy.hstack()` / `numpy.vstack()` / `numpy.dstack()` funksiyalaridan foydalanish**

`numpy.hstack()`, `numpy.vstack()` va `numpy.dstack()` funksiyalari `concatenate` funksiyasining qulay "o‘ramlari" (wrappers) bo‘lib, massivlarni gorizontal, vertikal yoki chuqurlik bo‘ylab taxlash (stacking) uchun ishlatiladi. Ular kodni yanada o‘qishli va tushunarli qiladi.



**Misol**

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Gorizontal taxlash
res_h = np.hstack((a, b))
print("np.hstack: ", res_h)

# Vertikal taxlash
res_v = np.vstack((a, b))
print("np.vstack: ", res_v)

# Chuqurlik bo‘ylab taxlash
res_d = np.dstack((a, b))
print("np.dstack: ", res_d)

np.hstack:  [1 2 3 4 5 6]
np.vstack:  [[1 2 3]
 [4 5 6]]
np.dstack:  [[[1 4]
  [2 5]
  [3 6]]]


* **hstack:** massivlarni bitta uzun massivga birlashtiradi.
* **vstack:** ularni 2D massivda qatorlar ko‘rinishida ustma-ust taxlaydi.
* **dstack:** ularni uchinchi o‘q (chuqurlik) bo‘ylab birlashtirib, 3D massiv hosil qiladi.



**Izoh:**
`dstack` funksiyasida birinchi massivning birinchi elementi bilan ikkinchi massivning birinchi elementi bitta chuqurlik qatlamiga tushadi (masalan, `[1 4]`). Bu usul rangli tasvirlar bilan ishlashda (RGB kanallarini birlashtirishda) juda ko‘p qo‘llaniladi.

### **3. `numpy.stack()` funksiyasidan foydalanish**

`numpy.stack()` massivlarni **yangi o‘q** bo‘ylab birlashtiradi va natijada o‘lchovlar sonini (dimensionality) oshiradi. Bu usul massivlarni birlashtirish bilan birga, ularni yangi o‘lchovda alohida saqlab qolishni xohlaganingizda foydali bo‘ladi.



**Misol**

In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Massivlarni 1-o'q bo'ylab taxlash
res = np.stack((a, b), axis=1)

print(res)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


`axis=1` parametri bilan ishlatilgan `stack` funksiyasi elementlarni juftlik holatida yonma-yon qatorlarga birlashtiradi. Natijada har bir qatori har bir massivdan bittadan elementni o‘z ichiga olgan 2D massiv hosil bo‘ladi.


### **4. `numpy.block()` funksiyasidan foydalanish**

`numpy.block()` massivlarni ichma-ich bloklardan xuddi matrisalarni kichikroq sub-massivlardan yig‘gandek quradi. U murakkab massiv maketlarini yaratish uchun moslashuvchan va kuchli vositadir.



**Misol**

In [6]:
b1 = np.array([[1, 1], [1, 1]])
b2 = np.array([[2, 2, 2], [2, 2, 2]])
b3 = np.array([[3, 3], [3, 3], [3, 3]])
b4 = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]])

# Bloklarni joylashtirish
res = np.block([
    [b1, b2],
    [b3, b4]
])

print(res)

[[1 1 2 2 2]
 [1 1 2 2 2]
 [3 3 4 4 4]
 [3 3 4 4 4]
 [3 3 4 4 4]]


To‘rtta kichik massiv bloklar ko‘rinishida joylashtirilgan: `b1` va `b2` yuqorida yonma-yon, `b3` va `b4` esa ularning ostida yonma-yon. `np.block()` ushbu tartibni saqlagan holda ularni bitta yirik massivga birlashtiradi.

**Eslatma:** `np.block` ishlatayotganda bloklar o‘lchami mos kelishi kerak. Masalan, bir qatorda turgan bloklarning balandligi (qatorlar soni) bir xil bo‘lishi shart.

### 1.7.2. 1-D va 2-D massivlarni birlashtirish (Combining 1-D and 2-D Arrays)

Ba'zan 1-D massivni 2-D massiv bilan birlashtirish va ularning elementlari ustida birgalikda takrorlanish (iteratsiya) talab qilinadi. NumPy `numpy.nditer()` funksiyasi yordamida bu vazifani osonlashtiradi.

**Misol:** Ushbu oddiy kod `nditer()` yordamida 1-D va 2-D massivlarni qanday birgalikda qo'llash mumkinligini ko'rsatadi.


In [7]:
num1 = np.array([1, 2])
num2 = np.array([[10, 20],
                 [30, 40]])
                   
for a, b in np.nditer([num1, num2]):
    print(a, ":", b)

1 : 10
2 : 20
1 : 30
2 : 40


Bu yerda 1-D massiv elementlari 2-D massiv bilan juftlik hosil qilish uchun qatorlar bo'yicha takrorlanadi.

### **`nditer` funksiyasi**

NumPy-dagi `nditer` funksiyasi — bu massivlar turli shaklga (shape) ega bo‘lsa ham, ularni samarali aylanib chiqish (loop) imkonini beruvchi iteratordir. Unga ikkita massiv (masalan, 1-D va 2-D) berilsa, u elementlarni o‘zaro juftlaydi va ularni birgalikda qayta ishlashga sharoit yaratadi.

**Sintaksis**
`np.nditer([massiv1, massiv2])`



### **Misol**

Ushbu misolda biz 5 ta elementdan iborat 1-D massivni 2x5 o‘lchamli 2-D massiv bilan birlashtiramiz va ularni birgalikda ko‘rsatamiz.

In [8]:
num1 = np.arange(5)
print("1D massiv:")
print(num1)

num2 = np.arange(10).reshape(2, 5)
print("\n2D massiv:")
print(num2)

# 1-D va 2-D massivlarni birlashtirib iteratsiya qilish
for a, b in np.nditer([num1, num2]):
    print("%d:%d" % (a, b))

1D massiv:
[0 1 2 3 4]

2D massiv:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


E'tibor bering, 1-D massiv 2-D massivning qatorlariga mos kelishi uchun o'z-o'zini takrorlamoqda.

**2-misol:** Endi uzunroq 1-D massiv va kattaroq 2-D massiv bilan sinab ko'ramiz.


In [9]:
num1 = np.arange(7)
print("1D massiv:")
print(num1)

num2 = np.arange(21).reshape(3, 7)
print("\n2D massiv:")
print(num2)

# nditer yordamida birgalikda aylanish
for a, b in np.nditer([num1, num2]):
    print("%d:%d" % (a, b))

1D massiv:
[0 1 2 3 4 5 6]

2D massiv:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
0:0
1:1
2:2
3:3
4:4
5:5
6:6
0:7
1:8
2:9
3:10
4:11
5:12
6:13
0:14
1:15
2:16
3:17
4:18
5:19
6:20


**Izoh:**
Bu misolda 1-D massiv (7 ta element) 2-D massivning (3x7 o'lchamli) har bir qatori bilan mos keladi. `nditer` funksiyasi 1-D massivni virtual ravishda 3 marta takrorlaydi (har bir qator uchun bir marta), natijada jami 21 ta juftlik hosil bo'ladi. Bu ma'lumotlarni tahlil qilishda bitta o'lchovli koeffitsientlarni ko'p o'lchamli ma'lumotlar to'plamiga nisbatan qo'llashda juda qo'l keladi.

**3-misol:** Bu yerda 1-D massiv atigi 2 ta elementdan iborat, ammo 2-D massiv ko'plab qatorlarga ega.


In [10]:
num1 = np.arange(2)
print("1D massiv:")
print(num1)

num2 = np.arange(12).reshape(6, 2)
print("\n2D massiv:")
print(num2)

# nditer yordamida juftliklarni chiqarish
for a, b in np.nditer([num1, num2]):
    print("%d:%d" % (a, b))

1D massiv:
[0 1]

2D massiv:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
0:0
1:1
0:2
1:3
0:4
1:5
0:6
1:7
0:8
1:9
0:10
1:11


**Izoh:**
Ushbu misolda `num1` massivi `[0, 1]` ko'rinishida. 2-D massiv (`num2`) esa 6 ta qator va 2 ta ustundan iborat. `nditer` funksiyasi `num1` ning har bir elementini `num2` ning mos ustunidagi elementlar bilan juftlaydi. 1-D massiv 2-D massivning barcha 6 ta qatori bilan moslashish uchun jami 6 marta takrorlanadi. Bu "Broadcasting" (translyatsiya) mexanizmining yaqqol namunasidir.