In [2]:
from IPython.display import display, HTML

display(HTML("""
<style>
    /* 1. UMUMIY KONTEYNER VA SHRIFT */
    .rendered_html, .jp-RenderedHTMLCommon, .jp-RenderedMarkdown {
        font-family: "Times New Roman", Times, serif !important;
        color: black !important;
        font-feature-settings: "kern" 1, "liga" 1, "clig" 1, "dlig" 1 !important;
        -webkit-font-smoothing: antialiased !important;
    }

    /* 2. MATNLAR: 1.5 oraliq, abzats va ro‘yxatlar */
    .rendered_html p, .jp-RenderedHTMLCommon p {
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-align: justify !important;
        text-indent: 1.25cm !important; /* Faqat p uchun abzats */
        margin: 0 !important;
    }

    /* Ro‘yxatlar uchun maxsus (nuqtalarni qaytarish) */
    .rendered_html ul, .jp-RenderedHTMLCommon ul {
        list-style-type: disc !important;
        margin-left: 2.5cm !important; /* Nuqtalar ko‘rinishi uchun surish */
        padding: 0 !important;
        text-indent: 0 !important;
    }

    .rendered_html li, .jp-RenderedHTMLCommon li {
        display: list-item !important; /* Block-dan list-item-ga qaytarish */
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-indent: 0 !important;
        margin: 0 !important;
    }

    .rendered_html p, .jp-RenderedHTMLCommon p {
        text-indent: 1.25cm !important;
    }

    /* 3. SARLAVHALAR: Markazda */
    .rendered_html h1, .jp-RenderedHTMLCommon h1,
    .rendered_html h2, .jp-RenderedHTMLCommon h2,
    .rendered_html h3, .jp-RenderedHTMLCommon h3 {
        font-family: "Times New Roman", Times, serif !important;
        text-align: center !important;
        text-indent: 0 !important;
        margin: 0.5em 0 !important;
        font-weight: bold !important;
    }
    
    /* 4. KOD BLOKLARI VA PROMPTLARNI (In/Out) YASHIRISH */
    :root {
        --jp-code-font-size: 12pt !important;
    }

    /* "In [ ]" va "Out [ ]" yozuvlarini butunlay yo‘qotish */
    .jp-InputPrompt, .jp-OutputPrompt, .prompt, .input_prompt, .output_prompt {
        display: none !important;
        width: 0 !important;
        visibility: hidden !important;
    }

    /* Kod bloklarini chap chekkaga taqash */
    .jp-CodeCell .jp-Cell-inputWrapper, .cell.code_cell .input {
        margin-left: 0 !important;
        padding-left: 0 !important;
    }

    /* Sliderni yo‘qotish va qatorni majburan sindirish */
    .jp-CodeMirror, .CodeMirror, .CodeMirror-scroll, .CodeMirror-sizer, .CodeMirror-lines,
    .jp-OutputArea-output pre, .output_area pre, 
    .CodeMirror-code, .CodeMirror-line,
    code, kbd, samp {
        font-family: "Consolas", monospace !important;
        font-size: 12pt !important;
        text-indent: 0 !important;
        line-height: 1.3 !important;
        white-space: pre-wrap !important;
        word-wrap: break-word !important;
        word-break: break-all !important;
        overflow-x: visible !important;
        height: auto !important;
    }

    /* 5. BIRINCHI KATAKCHANI YASHIRISH VA TANLANGANDA OCHISH */
    /* Odatiy holatda mutlaqo yashirin va umuman joy egallamaydi */
    .jp-Notebook .jp-Cell:first-child:not(.jp-mod-selected), 
    .container div.cell.code_cell:first-of-type:not(.selected) {
        position: absolute !important;
        height: 0 !important;
        min-height: 0 !important;
        width: 0 !important;
        margin: 0 !important;
        padding: 0 !important;
        border: none !important;
        overflow: hidden !important;
        opacity: 0 !important;
        pointer-events: none !important;
        visibility: hidden !important;
    }    

    /* Katakcha tanlanganda (Ctrl+A bosilganda) to‘liq ochiladi */
    .jp-Notebook .jp-Cell:first-child.jp-mod-selected,
    .container div.cell.code_cell:first-of-type.selected {
        position: relative !important;
        height: auto !important;
        width: 100% !important;
        opacity: 1 !important;
        overflow: visible !important;
        pointer-events: auto !important;
        visibility: visible !important;
    }
</style>
"""))


# 2-O'lchamli Numpy Massivlari (2D Arrays)

Ushbu darslikda biz Numpy kutubxonasida ikki o'lchamli massivlar bilan ishlash asoslarini, ularning atributlarini va ular ustida bajariladigan matematik amallarni ko'rib chiqamiz.

## 1. Kirish va massiv yaratish

Ikki o'lchamli massivni (matritsani) yaratish uchun biz ichma-ich joylashgan ro'yxatlardan foydalanamiz.


In [3]:
import numpy as np

# Ichma-ich joylashgan ro'yxat yaratish
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]

# Ro'yxatni Numpy massiviga o'tkazish
A = np.array(a)
print("Matritsa A:\n", A)

Matritsa A:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


## 2. Massiv Atributlari

Numpy massivlarining asosiy xususiyatlarini quyidagi atributlar orqali aniqlash mumkin:

* **`ndim`**: O'lchamlar soni (rank). 2D massivlar uchun bu doim 2 ga teng.
* **`shape`**: Massivning shakli (qatorlar va ustunlar soni).
* **`size`**: Massivdagi jami elementlar soni.

In [4]:
# O'lchamlar sonini aniqlash
print("O'lchami (ndim):", A.ndim)

# Shaklini aniqlash (qatorlar, ustunlar)
print("Shakli (shape):", A.shape)

# Jami elementlar soni
print("Elementlar soni (size):", A.size)

O'lchami (ndim): 2
Shakli (shape): (3, 3)
Elementlar soni (size): 9


## 3. Indekslash va Kesish (Indexing & Slicing)

Elementlarga murojaat qilish uchun kvadrat qavslardan `[qator, ustun]` ko'rinishida foydalanamiz.

In [5]:
# Ikkinchi qator, uchinchi ustun elementini olish (indeks 0 dan boshlanadi)
# A[1][2] yoki A[1, 2] ko'rinishida yozish mumkin
print("Element A[1, 2]:", A[1, 2]) # Natija: 23

# Birinchi qatorning birinchi elementini olish
print("Element A[0, 0]:", A[0, 0]) # Natija: 11

# Slicing (Kesish): Birinchi qatorning dastlabki ikki elementini olish
print("Kesish A[0, 0:2]:", A[0, 0:2])

# Dastlabki ikki qatorning oxirgi ustunini olish
print("Kesish A[0:2, 2]:", A[0:2, 2])

Element A[1, 2]: 23
Element A[0, 0]: 11
Kesish A[0, 0:2]: [11 12]
Kesish A[0:2, 2]: [13 23]


## 4. Matematik Amallar

### 4.1. Massivlarni Qo'shish
Ikki massivni qo'shish elementma-element bajariladi. Ikkala massivning shakli (shape) bir xil bo'lishi kerak.

In [6]:
X = np.array([[1, 0], [0, 1]])
Y = np.array([[2, 1], [1, 2]])

Z = X + Y
print("X + Y natijasi:\n", Z)

X + Y natijasi:
 [[3 1]
 [1 3]]


### 4.2. Skalyar Ko'paytirish
Massivni biror songa ko'paytirganda, uning har bir elementi shu songa ko'paytiriladi.

In [7]:
Z = 2 * Y
print("2 * Y natijasi:\n", Z)

2 * Y natijasi:
 [[4 2]
 [2 4]]


### 4.3. Elementma-element ko'paytirish (Hadamard Product)
`*` operatori orqali ikki massivning mos elementlari bir-biriga ko'paytiriladi.

In [8]:
Z = X * Y
print("Elementma-element ko'paytirish (X * Y):\n", Z)

Elementma-element ko'paytirish (X * Y):
 [[2 0]
 [0 2]]


### 4.4. Matritsaviy ko'paytirish (Dot Product)
Haqiqiy matritsalar ko'paytmasini hisoblash uchun `np.dot()` funksiyasidan foydalaniladi. Bunda birinchi matritsaning ustunlar soni ikkinchi matritsaning qatorlar soniga teng bo'lishi shart.


In [9]:
A = np.array([[0, 1, 1], [1, 0, 1]])
B = np.array([[1, 1], [1, 1], [-1, 1]])

C = np.dot(A, B)
print("Matritsaviy ko'paytma (Dot Product):\n", C)

Matritsaviy ko'paytma (Dot Product):
 [[0 2]
 [0 2]]
