In [1]:
from IPython.display import display, HTML

display(HTML("""
<style>
    /* 1. UMUMIY KONTEYNER VA SHRIFT */
    .rendered_html, .jp-RenderedHTMLCommon, .jp-RenderedMarkdown {
        font-family: "Times New Roman", Times, serif !important;
        color: black !important;
        font-feature-settings: "kern" 1, "liga" 1, "clig" 1, "dlig" 1 !important;
        -webkit-font-smoothing: antialiased !important;
    }

    /* 2. MATNLAR: 1.5 oraliq, abzats va ro‘yxatlar */
    .rendered_html p, .jp-RenderedHTMLCommon p {
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-align: justify !important;
        text-indent: 1.25cm !important; /* Faqat p uchun abzats */
        margin: 0 !important;
    }

    /* Ro‘yxatlar uchun maxsus (nuqtalarni qaytarish) */
    .rendered_html ul, .jp-RenderedHTMLCommon ul {
        list-style-type: disc !important;
        margin-left: 2.5cm !important; /* Nuqtalar ko‘rinishi uchun surish */
        padding: 0 !important;
        text-indent: 0 !important;
    }

    .rendered_html li, .jp-RenderedHTMLCommon li {
        display: list-item !important; /* Block-dan list-item-ga qaytarish */
        font-family: "Times New Roman", Times, serif !important;
        font-size: 14pt !important;
        line-height: 1.5 !important;
        text-indent: 0 !important;
        margin: 0 !important;
    }

    .rendered_html p, .jp-RenderedHTMLCommon p {
        text-indent: 1.25cm !important;
    }

    /* 3. SARLAVHALAR: Markazda */
    .rendered_html h1, .jp-RenderedHTMLCommon h1,
    .rendered_html h2, .jp-RenderedHTMLCommon h2,
    .rendered_html h3, .jp-RenderedHTMLCommon h3 {
        font-family: "Times New Roman", Times, serif !important;
        text-align: center !important;
        text-indent: 0 !important;
        margin: 0.5em 0 !important;
        font-weight: bold !important;
    }
    
    /* 4. KOD BLOKLARI VA PROMPTLARNI (In/Out) YASHIRISH */
    :root {
        --jp-code-font-size: 12pt !important;
    }

    /* "In [ ]" va "Out [ ]" yozuvlarini butunlay yo‘qotish */
    .jp-InputPrompt, .jp-OutputPrompt, .prompt, .input_prompt, .output_prompt {
        display: none !important;
        width: 0 !important;
        visibility: hidden !important;
    }

    /* Kod bloklarini chap chekkaga taqash */
    .jp-CodeCell .jp-Cell-inputWrapper, .cell.code_cell .input {
        margin-left: 0 !important;
        padding-left: 0 !important;
    }

    /* Sliderni yo‘qotish va qatorni majburan sindirish */
    .jp-CodeMirror, .CodeMirror, .CodeMirror-scroll, .CodeMirror-sizer, .CodeMirror-lines,
    .jp-OutputArea-output pre, .output_area pre, 
    .CodeMirror-code, .CodeMirror-line,
    code, kbd, samp {
        font-family: "Consolas", monospace !important;
        font-size: 12pt !important;
        text-indent: 0 !important;
        line-height: 1.3 !important;
        white-space: pre-wrap !important;
        word-wrap: break-word !important;
        word-break: break-all !important;
        overflow-x: visible !important;
        height: auto !important;
    }

    /* 5. BIRINCHI KATAKCHANI YASHIRISH VA TANLANGANDA OCHISH */
    /* Odatiy holatda mutlaqo yashirin va umuman joy egallamaydi */
    .jp-Notebook .jp-Cell:first-child:not(.jp-mod-selected), 
    .container div.cell.code_cell:first-of-type:not(.selected) {
        position: absolute !important;
        height: 0 !important;
        min-height: 0 !important;
        width: 0 !important;
        margin: 0 !important;
        padding: 0 !important;
        border: none !important;
        overflow: hidden !important;
        opacity: 0 !important;
        pointer-events: none !important;
        visibility: hidden !important;
    }    

    /* Katakcha tanlanganda (Ctrl+A bosilganda) to‘liq ochiladi */
    .jp-Notebook .jp-Cell:first-child.jp-mod-selected,
    .container div.cell.code_cell:first-of-type.selected {
        position: relative !important;
        height: auto !important;
        width: 100% !important;
        opacity: 1 !important;
        overflow: visible !important;
        pointer-events: auto !important;
        visibility: visible !important;
    }
</style>
"""))


# Python-da 2D Numpy

## Maqsadlar

Ushbu laboratoriya ishini yakunlaganingizdan so'ng, siz quyidagilarga qodir bo'lasiz:

  * `numpy` kutubxonasi bilan bemalol ishlash
  * `numpy` yordamida murakkab amallarni bajarish

<h2>Mundarija</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
<ul>
<li><a href="#Create-a-2D-Numpy-Array">2D Numpy massivini yaratish</a></li>
<li><a href="#Accessing-different-elements-of-a-Numpy-Array">Numpy massivining turli elementlariga murojaat qilish</a></li>
<li><a href="#Basic-Operations">Asosiy amallar</a></li>
</ul>

</div>

<hr>

## 2D Numpy massivini yaratish

In [2]:
# Kutubxonalarni yuklash

import numpy as np

Uchta **bir xil o'lchamdagi** ichma-ich ro'yxatlarni o'z ichiga olgan `a` ro'yxatini ko'rib chiqing.

In [3]:
# Ro'yxat yaratish

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

Biz ro'yxatni quyidagicha Numpy massiviga o'tkazishimiz mumkin:

In [4]:
# Ro'yxatni Numpy massiviga o'tkazish
# Har bir element bir xil turga ega

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Biz o'qlar yoki o'lchamlar sonini (rank deb ham ataladi) aniqlash uchun `ndim` atributidan foydalanishimiz mumkin.

In [5]:
# Numpy massivining o'lchamlarini ko'rsatish

A.ndim

2

`shape` atributi har bir o'lchamning kattaligi yoki elementlar soniga mos keladigan kortejni (tuple) qaytaradi.


In [6]:
# Numpy massivining shaklini (o'lchamini) ko'rsatish

A.shape

(3, 3)

Massivdagi elementlarning umumiy soni `size` atributi orqali aniqlanadi.

In [7]:
# Numpy massivining hajmini (elementlar sonini) ko'rsatish

A.size

9

## Numpy massivining turli elementlariga murojaat qilish
Massivning turli elementlariga murojaat qilish uchun to'rtburchak qavslardan foydalanishimiz mumkin. Quyidagi rasmda 3x3 o'lchamli massiv uchun to'rtburchak qavslar, ro'yxat va massiv ko'rinishi o'rtasidagi bog'liqlik ko'rsatilgan:

<img src="images/5.1. NumTwoEg.png" width="500">


Biz 2-qator, 3-ustun elementiga quyidagi rasmda ko'rsatilganidek murojaat qilishimiz mumkin:

<img src="images/5.2. NumTwoFT.png" width="400">


Biz shunchaki to'rtburchak qavslardan va o'zimizga kerakli elementga mos keladigan indekslardan foydalanamiz:

In [8]:
# Ikkinchi qator va uchinchi ustundagi elementga murojaat qilish

A[1, 2]

np.int64(23)

Elementlarni olish uchun biz quyidagi belgidan ham foydalanishimiz mumkin:

In [9]:
# Ikkinchi qator va uchinchi ustundagi elementga murojaat qilish

A[1][2]

np.int64(23)

Quyidagi rasmda ko'rsatilgan elementlarni ko'rib chiqing:

<img src="images/5.3. NumTwoFF.png" width="400">


Biz elementga quyidagicha murojaat qilishimiz mumkin:

In [10]:
# Birinchi qator va birinchi ustundagi elementga murojaat qilish

A[0][0]

np.int64(11)

Numpy massivlarida biz qirqish (slicing) usulidan ham foydalanishimiz mumkin. Quyidagi rasmga e'tibor bering. Biz birinchi qatordagi dastlabki ikkita ustunni olmoqchimiz:

<img src="images/5.4. NumTwoFSF.png" width="400">


Buni quyidagi sintaksis yordamida amalga oshirish mumkin:

In [11]:
# Birinchi qatorning birinchi va ikkinchi ustunlaridagi elementlarga murojaat qilish

A[0][0:2]

array([11, 12])

Shuningdek, biz uchinchi ustunning dastlabki ikkita qatorini quyidagicha olishimiz mumkin:

In [12]:
# Birinchi va ikkinchi qatorlar hamda uchinchi ustundagi elementlarga murojaat qilish

A[0:2, 2]

array([13, 23])

Quyidagi rasmga muvofiq:

<img src="images/5.5. 2D_numpy.png" width="400"><br />


## Asosiy amallar

Biz massivlarni qo'shishimiz ham mumkin. Bu jarayon matritsalarni qo'shish bilan bir xil. `X` va `Y` matritsalarining qo'shilishi quyidagi rasmda ko'rsatilgan:

<img src="images/5.6. NumTwoAdd.png" width="500">


Numpy massivlari `X` va `Y` orqali berilgan:

In [13]:
# Numpy massivini yaratish X

X = np.array([[1, 0], [0, 1]])
X

array([[1, 0],
       [0, 1]])

In [14]:
# Numpy massivini yaratish Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

Numpy massivlarini quyidagicha qo'shishimiz mumkin:


In [15]:
# X va Y ni qo'shish

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Numpy massivini skalyar songa ko'paytirish, matritsani skalyar songa ko'paytirish bilan bir xil. Agar biz `Y` matritsasini 2 skalyar soniga ko'paytirsak, rasmda ko'rsatilganidek, matritsaning har bir elementini shunchaki 2 ga ko'paytiramiz.

<img src="images/5.7. NumTwoDb.png" width="500">


Numpy'da ham xuddi shu amalni quyidagicha bajarishimiz mumkin:

In [16]:
# Numpy massivini yaratish Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [17]:
# Y ni 2 ga ko'paytirish

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

Ikki massivni ko'paytirish elementma-element ko'paytirishga yoki *Adamar ko'paytmasiga (Hadamard product)* mos keladi. `X` va `Y` matritsalarini ko'rib chiqing. Adamar ko'paytmasi bir xil pozitsiyadagi elementlarni o'zaro ko'paytirishni anglatadi, ya'ni bir xil rangdagi kataklarda joylashgan elementlar bir-biriga ko'paytiriladi. Natijada, quyidagi rasmda ko'rsatilganidek, o'lchami `Y` yoki `X` matritsasi bilan bir xil bo'lgan yangi matritsa hosil bo'ladi.

<img src="images/5.8. NumTwoMul.png" width="500">


`X` va `Y` massivlarining elementma-element ko'paytmasini quyidagicha bajarishimiz mumkin:

In [18]:
# Numpy massivini yaratish Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [19]:
# Numpy massivini yaratish X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [20]:
# X ni Y ga ko'paytirish

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

Numpy massivlari `A` va `B` bilan matritsali ko'paytirishni quyidagicha bajarishimiz mumkin:
Dastlab, `A` va `B` matritsalarini aniqlaymiz:


In [21]:
# A matritsasini yaratish

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [22]:
# B matritsasini yaratish

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

Massivlarni o'zaro ko'paytirish uchun numpy'ning `dot` funksiyasidan foydalanamiz.

In [23]:
# Skalyar ko'paytmani (dot product) hisoblash

Z = np.dot(A, B)
Z

array([[0, 2],
       [0, 2]])

In [24]:
# Z ning sinusini hisoblash

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

Matritsani transponirlanganini hisoblash uchun biz numpy-ning `T` atributidan foydalanamiz:

In [26]:
# C matritsasini yaratish

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [27]:
# C ning transponirlanganini olish

C.T

array([[1, 2, 3],
       [1, 2, 3]])

## 2D Numpy massivi bo'yicha viktorina

Quyidagi `a` ro'yxatini ko'rib chiqing va uni Numpy massiviga o'tkazing:

In [28]:
# Kodni pastga yozing va bajarish uchun Shift+Enter tugmalarini bosing

a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

<details><summary>Yechimni ko'rish uchun bu yerni bosing</summary>

```python
A = np.array(a)
A
```

</details>

Numpy massivining o'lchamini (elementlar sonini) hisoblang:

In [29]:
# Kodni pastga yozing va bajarish uchun Shift+Enter tugmalarini bosing

<details><summary>Yechimni ko'rish uchun bu yerni bosing</summary>

```python
A.size
```

</details>

Birinchi qator, birinchi va ikkinchi ustundagi elementlarga murojaat qiling:

In [30]:
# Kodni pastga yozing va bajarish uchun Shift+Enter tugmalarini bosing

<details><summary>Yechimni ko'rish uchun bu yerni bosing</summary>

```python
A[0][0:2]
```

</details>


Numpy massivlari `A` va `B` bilan matritsali ko'paytirishni bajaring:

In [31]:
# Kodni pastga yozing va bajarish uchun Shift+Enter tugmalarini bosing

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

<details><summary>Yechimni ko'rish uchun bu yerni bosing</summary>

```python
X = np.dot(A,B)
X
```

</details>


<hr>
<h2>Oxirgi mashq!</h2>
<p>Tabriklaymiz, siz Python bo'yicha birinchi darsingizni va amaliy mashg'ulotingizni muvaffaqiyatli yakunladingiz.
<hr>

## Numpy bo'yicha amaliy viktorina:

**1. Qaysi Python kutubxonasi Pandas uchun asos bo'lib xizmat qiladi va ilmiy hisoblashlar uchun ishlatiladi?**
<br>
<input type="radio" name="q1"> OS <br>
<input type="radio" name="q1"> Numpy <br>
<input type="radio" name="q1"> Requests <br>
<input type="radio" name="q1"> datetime <br>

**2. Qaysi atribut numpy massividagi elementlar sonini qaytaradi?**
<br>
<input type="radio" name="q2"> a.dtype <br>
<input type="radio" name="q2"> a.size <br>
<input type="radio" name="q2"> a.shape <br>
<input type="radio" name="q2"> a.ndim <br>

**3. Ushbu massivdagi birinchi elementni qanday qilib 10 ga o'zgartirasiz? `c = np.array([100, 1, 2, 3, 0])`**
<br>
<input type="radio" name="q3"> c[1]=10 <br>
<input type="radio" name="q3"> c[0]=10 <br>
<input type="radio" name="q3"> c[2]=10 <br>
<input type="radio" name="q3"> c[4]=10 <br>