<h1>📘 NumPy kutubxonasi haqida umumiy ma’lumot</h1>

<h4>
5-Mavzu: Mashinali o‘qitishda NumPy va Pandas paketlarining qo‘llanilishi.

2-mashg‘ulot. **NumPy va Pandas bilan ma’lumotlarni qayta ishlash**

                O‘quv savollari:
1. NumPy kutubxonasida amallar bajarish
2. Pandas yordamida ma’lumotlarni qayta ishlash va tahlil qilish.
</h4>

<h3 style="text-align: center">1-o'quv savoli: <b>1. NumPy kutubxonasida amallar bajarish</b></h3> 


<h3>1. NumPy nima?</h3>

**NumPy (Numerical Python)** — bu Python dasturlash tilida ilmiy va matematik hisob-kitoblar uchun eng asosiy kutubxonalardan biridir. NumPy massivlar (array) bilan ishlashni osonlashtiradi va an’anaviy Python ro‘yxatlariga qaraganda tezroq, ixcham va samaraliroq hisoblanadi.

NumPy:
* katta hajmdagi sonli ma’lumotlar bilan ishlaydi,
* matritsa va vektorlar ustida amallarni bajaradi,
* statistik, matematik va chiziqli algebra funksiyalarini taqdim etadi,
* boshqa ML kutubxonalari (Pandas, Scikit-Learn, TensorFlow, PyTorch) uchun asos bo‘lib xizmat qiladi.

NumPy amallari oddiy Python looplari orqali emas, balki **C darajasida yozilgan vektorlashgan funksiyalar** orqali bajariladi.

Bu shuni anglatadi:

* Python har bir elementni for bilan aylanmaydi

* Birinchi darajada bitta buyruq barcha elementlarga qo‘llanadi

* CPU’ning SIMD (Single Instruction Multiple Data) registrlari ishlatiladi

**Vektorlashgan hisoblash (vectorized computing)** – bu hisoblash jarayonini **elementma-element emas**, balki **bir nechta elementni bir vaqtning o‘zida** (blok holida) bajaradigan optimallashtirilgan usuldir.

<table>
  <tr>
    <td><img src="Rasmlar/1_krn3NPwCERy6hk0xKB5CZQ.png" width="500"></td>
    <td><img src="Rasmlar/np-vectorize-thumbnail.webp" width="500"></td>
  </tr>
  <tr>
    <td><img src="Rasmlar/SIMD-Vectorization-for-Faster-Analytical-Queries_scalar-vs-vectorized-diagram.png" width="500"></td>
    <td><img src="Rasmlar/simd.jpg" width="500"></td>
  </tr>
</table>


Sodda qilib aytganda:

> **Oddiy usul:** bir xil operatsiyani 1 ta elementga
> **Vektorlashgan usul:** shu operatsiyani 1000 ta elementga *bir yo‘la* bajaradi.

---

# Nega bunga “vektorlashgan” deyishadi?

Chunki ma’lumotlar **vektorlar** (ya’ni elementlar ketma-ketligi) ko‘rinishida qayta ishlanadi:

* numpy massivlari
* GPU/CPU SIMD registrlari
* parallel instruktsiyalar

---

# Oddiy misol (Python – oddiy sikl)




In [7]:
result = []
for x in [1, 2, 3, 4]:
    result.append(x * 2)

Bu yerda Python **har bir elementni alohida hisoblaydi** → sekinroq.

---

# Vektorlashgan misol (NumPy)

In [17]:
import numpy as np

In [18]:
x = np.array([1, 2, 3, 4])
result = x * 2

Bu yerda NumPy **SIMD** (Single Instruction, Multiple Data) orqali
→ **barcha elementlarga bir yo‘la** ko‘paytirish bajaradi
→ **juda tez ishlaydi**.

---

# Vektorlashgan hisoblashning afzalliklari

| Afzallik                  | Izoh                                                |
| ------------------------- | --------------------------------------------------- |
| **Tez ishlaydi**          | Bir nechta elementni bir vaqtning o‘zida hisoblaydi |
| **Kam xotira harakati**   | Loop overhead yo‘q, CPU keshlari yaxshi ishlaydi    |
| **GPUga mos**             | GPUlar minglab operatsiyani paralel bajaradi        |
| **Kod qisqa va chiroyli** | “x * 2” kabi oddiy yoziladi                         |

---

# Qayerda ishlatiladi?

* NumPy, Pandas
* Deep Learning kutubxonalari (PyTorch, TensorFlow)
* Matritsa amallari, statistik hisoblashlar
* GPU asosidagi hisoblashlar

---

# Xulosa

**Vektorlashgan hisoblash – bir xil operatsiyani ko‘p elementlarga bir vaqtning o‘zida bajarib, hisoblashni bir necha baravar tezlashtirish texnikasidir.**

Quyida, NumPy dagi **vectorization vs loop** bo‘yicha benchmark (tezlik solishtiruv) kodi keltirilgan.

---

## 1-qism: Oddiy Python ro‘yхati bilan hisoblash

In [11]:
import time

# 10 millionta elementli ro'yxat
n = 10_000_000
py_list = list(range(n))

start = time.time()
result = [x * 2 for x in py_list]
end = time.time()

print("Oddiy Python ro'yxati uchun vaqt:", end - start, "sekund")

Oddiy Python ro'yxati uchun vaqt: 0.6048295497894287 sekund


Bu yerda:

* `py_list` – oddiy Python ro‘yхat
* har bitta elementni `x * 2` qilib **list comprehension** orqali hisoblayapmiz
* `time.time()` orqali qancha vaqt ketganini o‘lchayapmiz

---

## 2-qism: NumPy vektorlashgan hisoblash


In [19]:
import time

n = 10_000_000
np_array = np.arange(n)

start = time.time()
result_np = np_array * 2
end = time.time()

print("NumPy vektorlashgan hisoblash vaqti:", end - start, "sekund")

NumPy vektorlashgan hisoblash vaqti: 0.034420013427734375 sekund


Bu yerda:

* `np_array` – NumPy massivi
* `np_array * 2` – **bitta yozuv bilan** barcha elementlarga operatsiya
* ichida C/Fortran darajasida optimallashtirilgan, SIMD va hokazo

---

## ⏱ 3-qism: %timeit bilan solishtirish (Jupyter uchun maxsus)

Jupyter Notebook’da `timeit` “sehrli” komandasi bor, uni ishlatsak yanada aniqroq bo‘ladi.

### Python ro‘yхati:

In [13]:
py_list = list(range(1_000_000))

%timeit [x * 2 for x in py_list]

56.8 ms ± 2.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### NumPy vektorlashgan:



In [20]:
np_array = np.arange(1_000_000)

%timeit np_array * 2

2.67 ms ± 172 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Natijada ko‘rasizki:

* NumPy vektorlashgan usuli **bir necha baravar tezroq** chiqadi.

---

Quyida **list, tuple, dictionary** kabi Python ma’lumot turlarini qanday qilib **NumPy array**ga aylantirish va ularning qanday farq qilishi tushuntirilgan:

---

# **1. List → NumPy array**

Python ro‘yxatini (list) to‘g‘ridan-to‘g‘ri massivga aylantirish eng oson variant.

### ✔ Oddiy list


In [21]:
lst = [1, 2, 3, 4]
arr = np.array(lst)
arr

array([1, 2, 3, 4])

### ✔ Ichma-ich list (2D list)

In [24]:
lst2 = [[1, 2, 3],
        [4, 5, 6]]

arr2 = np.array(lst2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

**Natija:** 2×3 matritsa.

**Eslatma:**
Har bir ichki ro‘yxat uzunligi teng bo‘lishi kerak, aks holda NumPy `dtype=object` bo‘lgan “gibrid” massiv yaratadi.

---

# **2. Tuple → NumPy array**

Tuple ham listga o‘xshaydi, faqat o‘zgarmas (immutable). NumPy uni ham 1×1 qabul qiladi:

### ✔ Oddiy tuple

In [27]:
tpl = (10, 20, 30)
arr = np.array(tpl)
arr

array([10, 20, 30])

### ✔ Ichki tuple

In [28]:
tpl2 = ((1, 2), (3, 4), (5, 6))
arr2 = np.array(tpl2)
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

NumPy buni 3×2 massiv deb oladi.

---

# **3. Dictionary → NumPy array**

**3 xil turi** mavjud.

---

## **3.1. Faqat qiymatlar (values)ni arrayga aylantirish**

Eng keng tarqalgan amaliy yechim:

In [29]:
d = {"a": 1, "b": 2, "c": 3}
arr = np.array(list(d.values()))
arr

array([1, 2, 3])

---
## **3.2. Kalitlar (keys)ni arrayga aylantirish**


In [30]:
np.array(list(d.keys()))

array(['a', 'b', 'c'], dtype='<U1')

---

## **3.3. Dictionary elementlarini juftlik (key-value pair) sifatida array qilish**


In [31]:
arr = np.array(list(d.items()))
arr

array([['a', '1'],
       ['b', '2'],
       ['c', '3']], dtype='<U21')

Bu massiv **2 ustunli** bo‘ladi: key va value.

---
# **Eslatma: Dictionary → np.array() bevosita berilsa nima bo‘ladi?**

In [32]:
np.array({"a":1, "b":2})

array({'a': 1, 'b': 2}, dtype=object)

Bu **xato emas**, lekin foydasiz, chunki **object-type** massiv boʻladi.
Shuning uchun dictionaryni oldin **list yoki tuple** ko‘rinishga o‘tkazib olish kerak.

---

# **4. Aralash ma’lumotlar (mixed types)**

Agar list, tuple yoki dict qiymatlari turli tipda bo‘lsa:



In [33]:
np.array([1, "salom", 3.5])

array(['1', 'salom', '3.5'], dtype='<U32')

NumPy **hammasini string**ga aylantiradi yoki `dtype=object` qiladi.

---

# **Xulosa jadvali**

| Python turi             | Arrayga aylantirish          | Eslatma                   |
| ----------------------- | ---------------------------- | ------------------------- |
| **List**                | `np.array(list)`             | Eng to‘g‘ridan-to‘g‘ri    |
| **Tuple**               | `np.array(tuple)`            | List bilan bir xil tarzda        |
| **Dictionary (values)** | `np.array(list(d.values()))` | Eng ko‘p ishlatiladi      |
| **Dictionary (keys)**   | `np.array(list(d.keys()))`   | Kalitlar massivini beradi |
| **Dictionary (items)**  | `np.array(list(d.items()))`  | 2D massiv hosil bo‘ladi   |

---

# NumPy massiv metodlari — umumiy jadval

Eng ko‘p ishlatiladigan metodlar (**kategoriyalar bo‘yicha**)

### Asosiy metodlar jadvali

| Kategoriya                   | Funktsiya / metod                     | Qisqa vazifasi                                           |
| ---------------------------- | ------------------------------------- | -------------------------------------------------------- |
| **Massiv yaratish**          | `np.array`                            | Python list/tuple/dict dan massiv yaratish               |
|                              | `np.zeros`, `np.ones`, `np.full`      | 0, 1 yoki berilgan qiymatga to‘ldirilgan massiv          |
|                              | `np.arange`, `np.linspace`            | Ketma-ket sonlar yaratish                                |
|                              | `np.eye`                              | Diagonal bo‘yicha 1 bo‘lgan kvadrat matritsa             |
|                              | `np.random.rand`, `np.random.randint` | Tasodifiy massivlar                                      |
| **Massiv haqida ma’lumot**   | `.ndim`, `.shape`, `.size`, `.dtype`  | O‘lchamlar soni, shakli, elementlar soni, turi           |
| **Shakl o‘zgartirish**       | `reshape`                             | Massiv shaklini o‘zgartirish                             |
|                              | `ravel`, `flatten`                    | Tekis (1D) ko‘rinishga keltirish                         |
|                              | `transpose`, `.T`, `swapaxes`         | O‘qlarni almashtirish                                    |
|                              | `expand_dims`, `squeeze`              | O‘lcham qo‘shish yoki siqish                             |
| **Tip o‘zgartirish**         | `astype`                              | Elementlarning turini o‘zgartirish (int → float va h.k.) |
| **Indekslash / tanlash**     | `[]` slicing                          | Kesish: `a[1:5, :]`                                      |
|                              | Boolean indexing                      | `a[a > 0]` kabi shart bilan tanlash                      |
|                              | Fancy indexing                        | `a[[0, 2, 5]]` bilan indekslar ro‘yxati bo‘yicha tanlash |
|                              | `np.where`                            | Shart bo‘yicha indeks yoki qiymat tanlash                |
| **Arifmetik va ufunc**       | `+ - * / **`                          | Elementma-element arifmetika                             |
|                              | `np.add`, `np.multiply`               | Ufunclar orqali arifmetika                               |
|                              | `np.sqrt`, `np.exp`, `np.log`         | Ilmiy funksiyalar                                        |
|                              | `np.sin`, `np.cos`, `np.tan`          | Trigonometrik funksiyalar                                |
| **Agregatsiya / statistika** | `sum`, `mean`, `min`, `max`           | Yig‘indi, o‘rtacha, min/max                              |
|                              | `std`, `var`                          | Standart og‘ish, dispersiya                              |
|                              | `argmin`, `argmax`                    | Min/max indeksini qaytarish                              |
|                              | `cumsum`, `cumprod`                   | Kumulativ yig‘indi, ko‘paytma                            |
| **Saralash / qidirish**      | `np.sort`, `.sort`                    | Elementlarni tartiblash                                  |
|                              | `np.argsort`                          | Saralash tartibidagi indekslar                           |
|                              | `np.unique`                           | Takrorlanmagan qiymatlar                                 |
|                              | `np.in1d`, `np.isin`                  | Elementlar boshqa massivda bormi?                        |
| **Birlashtirish**            | `np.concatenate`                      | Massivlarni bir yo‘nalishda ulash                        |
|                              | `np.stack`, `vstack`, `hstack`        | Yangi o‘lcham bo‘yicha ulash                             |
|                              | `np.column_stack`, `row_stack`        | Ustun/satr bo‘yicha ulash                                |
| **Bo‘lish (split)**          | `np.split`                            | Massivni teng qismlarga bo‘lish                          |
|                              | `np.hsplit`, `np.vsplit`              | Gorizontal/vertikal bo‘lish                              |
| **Nusxa / view**             | `.copy`, `np.copy`                    | To‘liq nusxa olish                                       |
|                              | `view`                                | Xotirani bo‘lishadigan qarash (view)                     |
| **Chiziqli algebra**         | `np.dot`, `@`, `np.matmul`            | Skalyar ko‘paytma, matritsa ko‘paytma                    |
|                              | `np.linalg.inv`                       | Matritsa teskari (inverse)                               |
|                              | `np.linalg.det`                       | Determinant                                              |
|                              | `np.linalg.eig`                       | O‘z qiymat va o‘z vektorlar                              |

Endi har bir kategoriyani **batafsil**, parametrlar va misollar bilan ko‘rib chiqamiz.

---

## 1. Massiv yaratish metodlari

### 1.1. `np.array`

**Vazifasi:** Python list/tuple/np array’dan yangi NumPy massivi yaratadi.
```python
np.array(object, dtype=None, copy=True)
```
* `object` – list, tuple, boshqa array va h.k.
* `dtype` – element turi (`np.int32`, `np.float64`, `np.bool_`, …)
* `copy` – `True` bo‘lsa, nusxa yaratadi; `False` bo‘lsa, imkon bo‘lsa, xotirani bo‘lishadi.

**Misol:**

In [38]:
lst = [1, 2, 3]
a = np.array(lst)          # dtype avtomatik
b = np.array(lst, dtype=float)  # float massiv

print(a, a.dtype)   # [1 2 3] int64 (masalan)
print(b, b.dtype)   # [1. 2. 3.] float64

[1 2 3] int64
[1. 2. 3.] float64


---

### 1.2. `np.zeros`, `np.ones`, `np.full`

**Vazifasi:** Berilgan shaklda 0, 1 yoki ma’lum qiymatga to‘ldirilgan massiv yaratadi.

```python
np.zeros(shape, dtype=float)
np.ones(shape, dtype=float)
np.full(shape, fill_value, dtype=None)
```
* `shape` – o‘lcham: `3`, `(2,3)`, `(2,2,2)` va boshqalar
* `fill_value` – to‘ldiriladigan qiymat
* `dtype` – element turi

**Misol:**

In [39]:
z = np.zeros((2, 3))               # 2x3 nol
o = np.ones((2, 2), dtype=int)     # 2x2 birlik, int
f = np.full((1, 4), 7.5)           # 1x4, hamma element 7.5

print(z)
print(o)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]]
[[7.5 7.5 7.5 7.5]]


---

### 1.3. `np.arange`, `np.linspace`

#### `np.arange`

**Vazifasi:** `range`ga o‘xshash, lekin array qaytaradi.
```python
np.arange(start, stop, step, dtype=None)
```

* `start` – boshlanish (standart: 0)
* `stop` – to‘xtash (kiritilmaydi)
* `step` – qadam (standart: 1)
* `dtype` – turi

**Misol:**

In [41]:
a = np.arange(5)         # 0,1,2,3,4
b = np.arange(1, 10, 2)  # 1,3,5,7,9
print(a)
print(b)

[0 1 2 3 4]
[1 3 5 7 9]


#### `np.linspace`

**Vazifasi:** [start, stop] oraliqni berilgan `num` bo‘lakka bo‘lib, massiv qaytaradi.

```python
np.linspace(start, stop, num=50, endpoint=True)
```

* `start` – boshlanish
* `stop` – oxiri
* `num` – elementlar soni
* `endpoint` – `True` bo‘lsa, `stop` ham kiradi

**Misol:**

In [42]:
x = np.linspace(0, 1, 5)
print(x)   # [0.   0.25 0.5  0.75 1.  ]

[0.   0.25 0.5  0.75 1.  ]


---

### 1.4. `np.eye`

**Vazifasi:** Diagonal bo‘yicha 1 bo‘lgan kvadrat / to‘rtburchak matritsa.

```python
np.eye(N, M=None, k=0, dtype=float)
```

* `N` – satrlar soni
* `M` – ustunlar soni (standart: `N`)
* `k` – qaysi diagonal: 0 – asosiy, 1 – yuqori, -1 – pastki
* `dtype` – element turi

**Misol:**

```python
I = np.eye(3)
print(I)
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

J = np.eye(3, 4, k=1)
print(J)
```

---

### 1.5. Tasodifiy massivlar — `np.random.rand`, `np.random.randint`

#### `np.random.rand`

**Vazifasi:** [0, 1) oraliqda bir xil taqsimlangan tasodifiy float’lar.

```python
np.random.rand(d0, d1, ...)
```

**Misol:**

```python
r = np.random.rand(2, 3)   # 2x3 tasodifiy son
print(r)
```

#### `np.random.randint`

**Vazifasi:** [low, high) oraliqda tasodifiy integer’lar.

```python
np.random.randint(low, high=None, size=None)
```

* `low` – pastki chegarasi (kiritiladi)
* `high` – yuqori chegarasi (kiritilmaydi)
* `size` – shakl (masalan `(2,3)`)

**Misol:**

```python
ri = np.random.randint(0, 10, size=(2, 4))
print(ri)
```

---

## 2. Massiv haqida ma’lumot metodlari

Bu metodlar array’ni “diagnostika qilish” uchun ishlatiladi.

```python
a = np.arange(12).reshape(3, 4)
print(a)
```

### 2.1. `.ndim`, `.shape`, `.size`, `.dtype`

**Vazifasi:**

* `ndim` – o‘lchamlar soni (1D, 2D, 3D…)
* `shape` – har bir o‘lcham bo‘yicha uzunlik
* `size` – jami elementlar soni
* `dtype` – elementlar turi

**Misol:**

```python
print("ndim:", a.ndim)    # 2
print("shape:", a.shape)  # (3, 4)
print("size:", a.size)    # 12
print("dtype:", a.dtype)  # int64 va hokazo
```

---

## 3. Shakl va o‘lcham bilan ishlash

### 3.1. `reshape`

**Vazifasi:** Massiv shaklini (o‘lchamini) o‘zgartirish.

```python
a.reshape(newshape)
```

* `newshape` – yangi shakl. Jami elementlar soni o‘zgarmasligi shart.
* `-1` ishlatilsa, o‘sha joy avtomatik hisoblanadi.

**Misol:**

```python
b = np.arange(12)
c = b.reshape(3, 4)
d = b.reshape(2, -1)   # 2 qator, ustunlarni o‘zi topadi

print(c)
print(d)
```

---

### 3.2. `ravel` va `flatten`

**Ikkalasi ham tekis (1D) ko‘rinishga keltiradi, farqi:**

* `ravel()` – imkon bo‘lsa view qaytaradi (xotira bo‘lishadi)
* `flatten()` – har doim nusxa (copy)

```python
b = np.arange(6).reshape(2, 3)
r = b.ravel()
f = b.flatten()

print(r)
print(f)
```

---

### 3.3. `transpose` va `.T`

**Vazifasi:** O‘qlarni (axis) almashtirish.

2D matritsa uchun `.T` — transponirlangan matritsa.

```python
a = np.arange(6).reshape(2, 3)
print(a)
print(a.T)
```

Ko‘p o‘lchamli massiv uchun:

```python
np.transpose(a, axes=(1, 0))
```

---

### 3.4. `swapaxes`

**Vazifasi:** Ikki o‘qning o‘rnini almashtirish.

```python
np.swapaxes(a, axis1, axis2)
```

---

### 3.5. `expand_dims` va `squeeze`

#### `np.expand_dims`

**Vazifasi:** Yangi o‘lcham qo‘shish (1D → 2D kabi).

```python
x = np.array([1, 2, 3])
y = np.expand_dims(x, axis=0)
print(x.shape)  # (3,)
print(y.shape)  # (1, 3)
```

#### `np.squeeze`

**Vazifasi:** O‘lchami 1 bo‘lgan o‘qlarni olib tashlaydi.

```python
z = np.array([[[1, 2, 3]]])   # shape (1,1,3)
print(z.shape)
zs = np.squeeze(z)
print(zs.shape)                # (3,)
```

---

## 4. Tip o‘zgartirish — `astype`

**Vazifasi:** Elementlarning ma’lumot turini o‘zgartirish.

```python
a.astype(dtype)
```

* `dtype` – `np.float32`, `np.int64`, `'float'`, `'int'`, `'bool'` va h.k.

**Misol:**

```python
a = np.array([1.2, 3.7, 4.0])
b = a.astype(int)
c = a.astype(bool)

print(b, b.dtype)  # [1 3 4] int64
print(c, c.dtype)  # [ True  True  True] bool
```

---

## 5. Indekslash va tanlash

### 5.1. Oddiy slicing

```python
a = np.arange(10)
print(a[2:7])      # indeks 2..6
print(a[::2])      # har 2-ta element
```

2D massivda:

```python
b = np.arange(12).reshape(3,4)
print(b[1, 2])     # 2-qator, 3-ustun
print(b[0:2, 1:3]) # 1-2-qatorlar, 2-3-ustunlar
print(b[:, 0])     # barcha qatorlar, 1-ustun
```

---

### 5.2. Boolean indexing

**Vazifasi:** Shart bo‘yicha element tanlash.

```python
a = np.array([1, 2, 3, 4, 5])
mask = a > 3
print(mask)        # [False False False  True  True]
print(a[mask])     # [4 5]
```

To‘g‘ridan-to‘g‘ri:

```python
print(a[a % 2 == 0])   # juftlar
```

---

### 5.3. Fancy indexing

**Vazifasi:** Indekslar list/array’i bo‘yicha element tanlash.

```python
a = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]
print(a[idx])   # [10 30 50]
```

2D misol:

```python
b = np.arange(12).reshape(3,4)
print(b[[0, 2], [1, 3]])  # (0,1) va (2,3) elementlar
```

---

### 5.4. `np.where`

**Vazifasi:**

* 1-variant: Shart bo‘yicha indekslar
* 2-variant: Shart bo‘yicha qiymat tanlash (if-else)

```python
a = np.array([1, 2, 3, 4, 5])

idx = np.where(a > 3)
print(idx)          # (array([3, 4]),)

b = np.where(a > 3, a, 0)
print(b)            # [0 0 0 4 5]
```

---

## 6. Arifmetik amallar va ufunc’lar

### 6.1. Elementma-element arifmetika

```python
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)    # [11 22 33]
print(a - b)    # [-9 -18 -27]
print(a * b)    # [10 40 90]
print(b / a)    # [10. 10. 10.]
print(a ** 2)   # [1 4 9]
```

Broadcasting:

```python
print(a + 5)    # [6 7 8]
```

---

### 6.2. Ufunc: `np.add`, `np.multiply` va boshqalar

```python
np.add(a, b)
np.multiply(a, b)
np.power(a, 2)
```

**Misol:**

```python
print(np.add(a, b))        # [11 22 33]
print(np.multiply(a, 2))   # [2 4 6]
print(np.power(a, 3))      # [1 8 27]
```

---

### 6.3. Ilmiy funksiyalar: `sqrt`, `exp`, `log`

```python
x = np.array([1.0, 2.0, 4.0])
print(np.sqrt(x))    # ildiz
print(np.exp(x))     # e**x
print(np.log(x))     # natural log
```

---

### 6.4. Trigonometrik funksiyalar

```python
t = np.array([0, np.pi/2, np.pi])
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))
```

---

## 7. Agregatsiya va statistika

Massiv bo‘yicha umumiy qiymatlar chiqarish.

### 7.1. `sum`, `mean`, `min`, `max`

```python
a = np.array([1, 2, 3, 4])

print(a.sum())   # 10
print(a.mean())  # 2.5
print(a.min())   # 1
print(a.max())   # 4
```

Axis bilan:

```python
b = np.arange(12).reshape(3, 4)

print(b.sum(axis=0))  # ustunlar bo‘yicha
print(b.sum(axis=1))  # qatorlar bo‘yicha
```

---

### 7.2. `std`, `var`

```python
print(a.std())   # standart og'ish
print(a.var())   # dispersiya
```

---

### 7.3. `argmin`, `argmax`

**Vazifasi:** Min/max elementning indeksini qaytaradi.

```python
a = np.array([5, 2, 9, 1])
print(a.argmin())   # 3 (qiymat 1)
print(a.argmax())   # 2 (qiymat 9)
```

2D uchun `axis` bilan:

```python
b = np.arange(12).reshape(3,4)
print(b.argmax(axis=1))   # har qatordagi eng katta element indeksi
```

---

### 7.4. `cumsum`, `cumprod`

```python
a = np.array([1, 2, 3, 4])

print(a.cumsum())   # [1 3 6 10]
print(a.cumprod())  # [1 2 6 24]
```

---

## 8. Saralash va qidirish

### 8.1. `np.sort` va `.sort`

**`np.sort(a)`** – yangi saralangan massiv qaytaradi (copy).
**`a.sort()`** – massivni o‘zida saralaydi (in-place).

```python
a = np.array([3, 1, 4, 1, 5])
print(np.sort(a))   # [1 1 3 4 5]
a.sort()
print(a)           # [1 1 3 4 5]
```

---

### 8.2. `np.argsort`

**Vazifasi:** Saralash uchun indekslar tartibini qaytaradi.

```python
a = np.array([30, 10, 20])
idx = np.argsort(a)
print(idx)       # [1 2 0]
print(a[idx])    # [10 20 30]
```

---

### 8.3. `np.unique`

**Vazifasi:** Takrorlanmaydigan elementlar.

```python
a = np.array([1, 2, 2, 3, 3, 3])
u = np.unique(a)
print(u)   # [1 2 3]
```

Parametrlar:

```python
np.unique(a, return_counts=True)
```

* `return_counts=True` bo‘lsa, har bir qiymat nechta ekanini ham qaytaradi.

```python
values, counts = np.unique(a, return_counts=True)
print(values)   # [1 2 3]
print(counts)   # [1 1 3]
```

---

## 9. Birlashtirish (concatenate, stack) va bo‘lish (split)

### 9.1. `np.concatenate`

```python
a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.concatenate([a, b])
print(c)   # [1 2 3 4 5]
```

2D misol:

```python
x = np.array([[1, 2],
              [3, 4]])
y = np.array([[5, 6]])

print(np.concatenate([x, y], axis=0))  # qator bo‘yicha
```

---

### 9.2. `np.stack`, `vstack`, `hstack`

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack([a, b], axis=0))  # 2x3
print(np.vstack([a, b]))         # xuddi shunga o‘xshash
print(np.hstack([a, b]))         # 1x6
```

---

### 9.3. `np.split`, `hsplit`, `vsplit`

```python
a = np.arange(10)
left, right = np.split(a, 2)
print(left, right)   # [0..4], [5..9]
```

2D:

```python
b = np.arange(16).reshape(4,4)
top, bottom = np.vsplit(b, 2)
left, right = np.hsplit(b, 2)
```

---

## 10. Nusxa va view — `.copy`, `view`

### 10.1. `copy`

```python
a = np.array([1, 2, 3])
b = a          # reference (xotira bo‘lishadi)
c = a.copy()   # yangi nusxa

a[0] = 99
print(b)   # [99  2  3]
print(c)   # [1 2 3]
```

`copy()` — alohida xotira.

`view()` — xuddi o‘sha xotiraga boshqa qarash.

Ko‘p hollarda `.copy()` bilan ishlash xavfsizroq.

---

## 11. Chiziqli algebra — `dot`, `@`, `np.linalg`

### 11.1. `dot` va `@`

```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(A.dot(B))
print(A @ B)        # xuddi shu
```

---

### 11.2. `np.linalg.inv`, `np.linalg.det`

```python
A = np.array([[1., 2.],
              [3., 4.]])

det = np.linalg.det(A)
invA = np.linalg.inv(A)

print("det:", det)
print("inv:\n", invA)
```

---

### 11.3. `np.linalg.eig`

```python
w, v = np.linalg.eig(A)   # o‘z qiymatlar va vektorlar
print("eigenvalues:", w)
print("eigenvectors:\n", v)
```

---

## Yakuniy fikr

Biz bu yerda:

* **asosiy metodlarni kategoriyalarga ajratdik**,
* **har birining vazifasi**, eng muhim **parametrlari**,
* va **kichik, tushunarli misollar** bilan ko‘rdik.

---

Agar xohlasangiz, keyingi qadamda:

* aynan shu materialni **alohida .ipynb notebook** strukturasida (masalan: 1-bo‘lim – massiv yaratish, 2-bo‘lim – indekslash, h.k.) bo‘lib,
* yoki **masalalar to‘plami** (har bo‘lim uchun 5–10 ta mashq) qilib ham tayyorlab bera olaman.
